
import ROLES from "./role.config";
import PERMISSIONS from "./permission.config";

const EMPLOYEE_PERMISSIONS = [
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.MANAGE_WORKERS,
  PERMISSIONS.MANAGE_FINANCE,
  PERMISSIONS.MANAGE_ANALYTICS,
  PERMISSIONS.MANAGE_COMPLAINT,
];

export default EMPLOYEE_PERMISSIONS;

