// Generated by the screenshot capture script — width/height of each
// /public/user-manual/<id>.webp, used to reserve space while images load.
const MANUAL_SHOTS = {
  "action-icons": {
    "w": 633,
    "h": 312
  },
  "activities-audit": {
    "w": 1400,
    "h": 885
  },
  "activities-login": {
    "w": 1400,
    "h": 885
  },
  "activity-detail": {
    "w": 1400,
    "h": 954
  },
  "admin-bell": {
    "w": 909,
    "h": 840
  },
  "agents": {
    "w": 1400,
    "h": 954
  },
  "autofill": {
    "w": 1400,
    "h": 954
  },
  "complaint-detail": {
    "w": 1400,
    "h": 954
  },
  "complaint-form": {
    "w": 1400,
    "h": 954
  },
  "complaints-list": {
    "w": 1400,
    "h": 885
  },
  "confirm": {
    "w": 1035,
    "h": 398
  },
  "content": {
    "w": 1400,
    "h": 954
  },
  "content-gallery": {
    "w": 1400,
    "h": 954
  },
  "content-location": {
    "w": 1400,
    "h": 954
  },
  "content-social": {
    "w": 1400,
    "h": 954
  },
  "dashboard-charts": {
    "w": 1400,
    "h": 954
  },
  "dashboard-top": {
    "w": 1400,
    "h": 954
  },
  "employee-create": {
    "w": 1400,
    "h": 954
  },
  "employee-create-mobile": {
    "w": 520,
    "h": 1125
  },
  "employee-cv": {
    "w": 1600,
    "h": 995
  },
  "employee-cv-shared": {
    "w": 1600,
    "h": 995
  },
  "employee-documents": {
    "w": 1226,
    "h": 509
  },
  "employee-files": {
    "w": 1170,
    "h": 591
  },
  "employee-include": {
    "w": 1136,
    "h": 486
  },
  "employee-preview": {
    "w": 1400,
    "h": 954
  },
  "employee-status": {
    "w": 1142,
    "h": 305
  },
  "employee-status-modal": {
    "w": 885,
    "h": 605
  },
  "employee-visa": {
    "w": 1400,
    "h": 954
  },
  "employees-archived": {
    "w": 1400,
    "h": 779
  },
  "employees-bulk": {
    "w": 1400,
    "h": 779
  },
  "employees-filters": {
    "w": 1400,
    "h": 143
  },
  "employees-list": {
    "w": 1400,
    "h": 779
  },
  "employees-report": {
    "w": 1400,
    "h": 779
  },
  "external-links": {
    "w": 1400,
    "h": 954
  },
  "finance-close": {
    "w": 855,
    "h": 894
  },
  "finance-list": {
    "w": 1400,
    "h": 885
  },
  "finance-new": {
    "w": 1400,
    "h": 954
  },
  "finance-periods": {
    "w": 1400,
    "h": 885
  },
  "finance-receipt": {
    "w": 1400,
    "h": 954
  },
  "forgot-password": {
    "w": 989,
    "h": 375
  },
  "invoice-detail": {
    "w": 1400,
    "h": 954
  },
  "invoice-form": {
    "w": 1358,
    "h": 1400
  },
  "invoice-payment": {
    "w": 1400,
    "h": 954
  },
  "invoice-print": {
    "w": 1400,
    "h": 954
  },
  "invoices-list": {
    "w": 1400,
    "h": 885
  },
  "layout": {
    "w": 1400,
    "h": 820
  },
  "letter": {
    "w": 1400,
    "h": 954
  },
  "login": {
    "w": 989,
    "h": 548
  },
  "manual": {
    "w": 1400,
    "h": 954
  },
  "messages-actions": {
    "w": 1120,
    "h": 760
  },
  "messages-filters": {
    "w": 1120,
    "h": 760
  },
  "messages-inbox": {
    "w": 1400,
    "h": 954
  },
  "messages-mobile": {
    "w": 520,
    "h": 1125
  },
  "messages-reply": {
    "w": 686,
    "h": 592
  },
  "messages-switch": {
    "w": 1120,
    "h": 420
  },
  "mobile-drawer": {
    "w": 520,
    "h": 1125
  },
  "mobile-header": {
    "w": 520,
    "h": 1125
  },
  "notifications-inbox": {
    "w": 1120,
    "h": 820
  },
  "notifications-send": {
    "w": 855,
    "h": 1061
  },
  "partner-cv": {
    "w": 1600,
    "h": 995
  },
  "partner-employees": {
    "w": 1400,
    "h": 885
  },
  "public-site": {
    "w": 1400,
    "h": 954
  },
  "settings-organization": {
    "w": 1400,
    "h": 954
  },
  "settings-password": {
    "w": 1400,
    "h": 954
  },
  "settings-profile": {
    "w": 1400,
    "h": 954
  },
  "sidebar-search": {
    "w": 930,
    "h": 495
  },
  "status": {
    "w": 1400,
    "h": 954
  },
  "tables": {
    "w": 1400,
    "h": 779
  },
  "tickets": {
    "w": 1400,
    "h": 954
  },
  "users-bulk": {
    "w": 1400,
    "h": 885
  },
  "users-create-partner": {
    "w": 1400,
    "h": 954
  },
  "users-create-staff": {
    "w": 1400,
    "h": 954
  },
  "users-list": {
    "w": 1400,
    "h": 885
  }
};

export default MANUAL_SHOTS;
