import ROLES from "../../../../config/role.config";

// ---------------------------------------------------------------------------
// User Manual content.
//
// Every module and topic carries an `access` rule (see utils/menuAccess.js):
//   paths     -> the user must be able to open at least one of these pages
//   allPaths  -> the user must be able to open every one of these pages
//   roles     -> only these roles
//   permission-> staff need this permission (admins always pass)
// A topic is shown only when both its module rule and its own rule pass, so
// the manual never documents a page the user cannot open.
//
// Screenshots live in /public/user-manual/<id>.webp and are real captures of
// the running system. `mobile: true` marks phone-sized captures.
//
// Writing style: short sentences and everyday words, so every staff member
// can follow them. Use the exact button and field names shown on screen.
// ---------------------------------------------------------------------------

const ADMIN = ROLES.ADMIN;
const STAFF = ROLES.EMPLOYEE;
const PARTNER = ROLES.PARTNER;

export const MANUAL_GROUPS = [
  { key: "basics", label: "Basics", icon: "bi-flag" },
  { key: "employees", label: "Employees", icon: "bi-person-check" },
  { key: "finance", label: "Money", icon: "bi-wallet2" },
  { key: "communication", label: "Messages", icon: "bi-chat-dots" },
  { key: "admin", label: "Admin", icon: "bi-shield-lock" },
  { key: "help", label: "Help", icon: "bi-life-preserver" },
];

const MANUAL_MODULES = [
  // ------------------------------------------------------------------ BASICS
  {
    id: "getting-started",
    group: "basics",
    title: "Getting Started",
    icon: "bi-flag",
    summary: "How to log in, move around and use the common buttons.",
    access: {},
    topics: [
      {
        id: "login",
        title: "Log in",
        summary: "Open the system with your email and password.",
        keywords: ["sign in", "password", "email", "account", "login"],
        where: "Login page",
        steps: [
          "Open the system in your browser.",
          "Type your email (1).",
          "Type your password (2).",
          "Click Log In (3).",
        ],
        shots: [
          {
            id: "login",
            caption: "Email (1), password (2), Log In (3). Forgot your password? Click (4).",
          },
        ],
        notes: [
          { type: "tip", text: "An admin makes your account. Ask them if you do not have one." },
          { type: "warning", text: "If you do nothing for a long time, the system logs you out. Just log in again." },
        ],
      },
      {
        id: "forgot-password",
        title: "Forgot your password",
        summary: "Get a code by email and make a new password.",
        keywords: ["reset", "otp", "code", "forgot", "password"],
        where: "Login page → Forgot Password?",
        steps: [
          "Click Forgot Password? on the login page.",
          "Type your email (1) and click Submit (2).",
          "Open your email and copy the code.",
          "Type the code and your new password. Click Reset Password.",
          "Log in with your new password.",
        ],
        shots: [{ id: "forgot-password", caption: "Type your email (1) and click Submit (2)." }],
        notes: [{ type: "tip", text: "The code works for a short time only. If it stops working, ask for a new one." }],
      },
      {
        id: "screen-layout",
        title: "The main screen",
        summary: "The menu, the page name, the bell and your name.",
        keywords: ["layout", "sidebar", "menu", "header", "bell", "navigation"],
        where: "Every page",
        steps: [
          "The menu on the left (1) shows the pages you can open. Your page is coloured.",
          "Click (2) to make the menu small or big.",
          "The page name is at the top (3).",
          "The bell (4) shows new messages. The red number is how many are new.",
          "Your name and role are on the right (5).",
        ],
        shots: [{ id: "layout", caption: "The parts of the screen." }],
        notes: [{ type: "tip", text: "You only see the pages you are allowed to use. If a page is missing, ask an admin." }],
      },
      {
        id: "sidebar-search",
        title: "Find a page fast",
        summary: "Type a page name in the menu.",
        keywords: ["search page", "find page", "sidebar search"],
        access: { roles: [ADMIN] },
        where: "Menu → Search page…",
        steps: [
          "Click Search page… at the top of the menu.",
          "Type part of the page name, for example fin.",
          "Click the page.",
        ],
        shots: [{ id: "sidebar-search", caption: "Type in the search box (1). Matching pages show below (2)." }],
      },
      {
        id: "mobile-menu",
        title: "Use it on a phone",
        summary: "Open the menu on a small screen.",
        keywords: ["mobile", "phone", "tablet", "drawer", "small screen"],
        where: "Phone or tablet",
        steps: [
          "On a phone the menu is hidden.",
          "Tap ☰ at the top right to open it.",
          "Tap a page. To close the menu, tap ×.",
          "Slide wide tables left and right with your finger.",
        ],
        shots: [
          { id: "mobile-header", caption: "Tap ☰ (1) to open the menu.", mobile: true },
          { id: "mobile-drawer", caption: "The menu on a phone. Tap × (1) to close it.", mobile: true },
        ],
      },
      {
        id: "tables",
        title: "Lists and filters",
        summary: "How every list works.",
        keywords: ["table", "list", "filter", "pagination", "clear filters", "search"],
        where: "Every list page",
        steps: [
          "Use the boxes at the top (1) to search or pick a choice. The list changes right away.",
          "Click Clear to show everything again.",
          "The small purple label (2) shows how many rows there are.",
          "Use the page numbers under the list to see more rows.",
          "The buttons at the end of a row (3) work on that row.",
        ],
        shots: [{ id: "tables", caption: "Filters, row count and row buttons." }],
      },
      {
        id: "action-icons",
        title: "Row buttons",
        summary: "What each small button does.",
        keywords: ["icons", "buttons", "view", "edit", "delete", "archive", "restore", "notify"],
        access: { roles: [ADMIN, STAFF] },
        where: "End of each row",
        steps: [
          "Eye – see the details.",
          "Pencil – change it.",
          "Bin – delete it.",
          "Person with a line – archive (hide it, but keep it).",
          "Round arrow – bring back an archived item.",
          "Bell – send a message to this person.",
          "Wallet – add a payment for this person.",
          "PDF – open the CV. Folder – see files. Passport – get the visa form.",
          "Put your mouse on a button to see its name.",
        ],
        shots: [{ id: "action-icons", caption: "Row buttons on the employee list." }],
        notes: [
          { type: "tip", text: "An admin can only change what they made. Items made by another admin are view only." },
        ],
      },
      {
        id: "confirm-messages",
        title: "Questions and messages",
        summary: "The system asks before risky actions and tells you the result.",
        keywords: ["confirm", "dialog", "modal", "success", "error", "message", "toast"],
        where: "Every page",
        steps: [
          "Before you delete or archive, the system asks “Are you sure?”.",
          "Click the coloured button to go on, or Cancel to stop.",
          "After you save, a message shows at the top. Green means done. Red tells you what is wrong.",
        ],
        shots: [{ id: "confirm", caption: "Click Archive (1) to go on, or Cancel (2) to stop." }],
        notes: [{ type: "warning", text: "Deleted items cannot come back. Use Archive if you only want to hide something." }],
      },
      {
        id: "open-manual",
        title: "Use this manual",
        summary: "Search and move around the manual.",
        keywords: ["help", "manual", "guide", "documentation", "toolkit"],
        where: "Menu → User Manual",
        steps: [
          "Click User Manual in the menu.",
          "Type in Search (1) to find a page or a job.",
          "Click a group (2) to see only that part.",
          "Click a topic in the Manual Menu (3).",
          "Click a picture to make it bigger.",
        ],
        shots: [{ id: "manual", caption: "The User Manual and its Toolkit." }],
        notes: [{ type: "tip", text: "The manual only shows the pages you can use." }],
      },
      {
        id: "logout",
        title: "Log out",
        summary: "Close your account safely.",
        keywords: ["logout", "sign out", "exit"],
        where: "Menu → Log Out",
        steps: ["Click Log Out at the bottom of the menu.", "Click Logout to confirm."],
        notes: [{ type: "warning", text: "Always log out on a shared computer." }],
      },
    ],
  },

  {
    id: "dashboard",
    group: "basics",
    title: "Dashboard",
    icon: "bi-speedometer2",
    summary: "Main numbers and charts about your workers.",
    access: { paths: ["/admin/dashboard"] },
    topics: [
      {
        id: "dashboard-kpis",
        title: "Main numbers",
        summary: "Totals and how many workers are at each step.",
        keywords: ["kpi", "total registered", "active workers", "tickets", "departed", "pipeline", "analytics"],
        where: "Menu → Dashboard",
        steps: [
          "The 4 cards (1) show: all registered, active workers, tickets given and workers who left in the last 30 days.",
          "Candidate Pipeline (2) shows how many workers are at each step now.",
        ],
        shots: [{ id: "dashboard-top", caption: "Number cards and workers per step." }],
      },
      {
        id: "dashboard-charts",
        title: "Charts",
        summary: "New workers per month, workers per partner and best agents.",
        keywords: ["chart", "trend", "partner", "agents", "graph"],
        where: "Dashboard (scroll down)",
        steps: [
          "Registration Trend: new workers each month.",
          "By Partner: workers for each partner.",
          "Top Agents: agents who brought the most workers.",
          "Put your mouse on a chart to see the number.",
        ],
        shots: [{ id: "dashboard-charts", caption: "The charts." }],
      },
      {
        id: "dashboard-activity",
        title: "Recent activity",
        summary: "Latest logins and changes by staff.",
        keywords: ["recent activity", "audit", "login"],
        access: { roles: [ADMIN] },
        where: "Dashboard (bottom)",
        steps: [
          "Recent Activity shows the newest logins and staff changes.",
          "To see everything, open Activities in the menu.",
        ],
        notes: [{ type: "tip", text: "Only admins see this." }],
      },
    ],
  },

  // ------------------------------------------------------------- EMPLOYEES
  {
    id: "employees",
    group: "employees",
    title: "Employees",
    icon: "bi-person-check",
    summary: "Add workers, keep their papers and steps up to date, make CVs and visa forms.",
    access: { paths: ["/admin/employees"] },
    topics: [
      {
        id: "employees-list",
        title: "Employee list",
        summary: "Find a worker and work with them.",
        keywords: ["employee list", "workers", "active employees", "find employee"],
        where: "Menu → Employees",
        steps: [
          "Click Employees in the menu.",
          "Add Employee (1) adds a new worker.",
          "Use the boxes (2) to find workers.",
          "Use the row buttons (3) to work with one worker.",
        ],
        shots: [{ id: "employees-list", caption: "The Active Employees page." }],
      },
      {
        id: "employees-filters",
        title: "Find workers",
        summary: "Search and pick choices to make the list shorter.",
        keywords: ["search", "filter", "passport number", "labour id", "status", "partner", "agent", "archived"],
        where: "Employees → boxes at the top",
        steps: [
          "Search (1): type a name, phone, passport number, labour ID or agent name.",
          "Status (2): show workers at one step.",
          "Partner (3): show workers with a contract for that partner.",
          "Agent (4): show workers from that agent.",
          "Active / Archived (5): show working or archived workers.",
          "Clear (6): remove all choices.",
        ],
        shots: [{ id: "employees-filters", caption: "Ways to find workers." }],
      },
      {
        id: "employee-view",
        title: "See a worker's details",
        summary: "All saved information on one page.",
        keywords: ["profile", "preview", "details", "view employee"],
        where: "Employees → eye button",
        steps: [
          "Click the eye button on the row.",
          "You see all the worker's information.",
          "Click a pencil next to a title to change that part.",
          "Click the back arrow to go back.",
        ],
        shots: [{ id: "employee-preview", caption: "A worker's details." }],
      },
      {
        id: "employee-create",
        title: "Add a new worker",
        summary: "Fill the form and save.",
        keywords: ["add employee", "create worker", "register", "new worker", "form"],
        where: "Employees → Add Employee",
        steps: [
          "Click Add Employee.",
          "You can click Upload Passport (1) and pick a clear photo of the passport. The name, number and dates fill in by themselves. Check them.",
          "Fill the boxes with a red *. They must be filled: Full Name, Phone Number, Sex, Region, Monthly Salary and the 2 photos.",
          "Under Status pick the first step, for example Registered.",
          "Fill the other parts you need. Click a part in the list (2) to go there. A green tick means it is done.",
          "Click Create Worker (3).",
        ],
        shots: [
          { id: "employee-create", caption: "Upload Passport (1), parts list (2), Create Worker (3)." },
          { id: "employee-create-mobile", caption: "On a phone the parts are a row at the top (1).", mobile: true },
        ],
        notes: [
          { type: "tip", text: "Phone numbers can have any country code and spaces, like +251 911 234 567." },
          { type: "warning", text: "Photos must be JPG, PNG or WEBP." },
        ],
      },
      {
        id: "employee-sections",
        title: "Extra parts and the Include switch",
        summary: "Passport, COC, medical, family contact, agent, visa, travel, contract, languages, skills and work history.",
        keywords: ["include", "passport", "coc", "medical", "emergency contact", "guarantor", "agent", "visa", "travel", "ticket", "contract", "languages", "skills", "experience"],
        where: "Worker form → extra parts",
        steps: [
          "Each extra part has an Include switch (1). Only parts that are switched on are saved.",
          "Passport: number, country and dates.",
          "COC: certificate number and test center.",
          "Medical: Fit, Unfit or Pending, and the clinic.",
          "Emergency Contact: a family member's name, phone and address.",
          "Agent Information: pick the agent and type the agent code. Both are needed.",
          "Visa: visa number and other visa numbers.",
          "Travel: ticket number, travel dates and city.",
          "Contract: employer, partner and contract status.",
          "Languages and Skills: tick what the worker can do. Experience: add the countries they worked in.",
          "When you change a worker, Reset (2) clears that part. The system asks first.",
        ],
        shots: [{ id: "employee-include", caption: "Include switch (1) and Reset (2)." }],
        notes: [{ type: "warning", text: "Reset deletes that part. Visa and Travel are cleared together." }],
      },
      {
        id: "employee-edit",
        title: "Change a worker",
        summary: "Change any part and save.",
        keywords: ["edit employee", "update worker", "save changes"],
        where: "Employees → pencil button",
        steps: [
          "Click the pencil button on the row.",
          "Change what you need.",
          "Click Save Changes at the top.",
        ],
        notes: [
          { type: "tip", text: "If you see “View only — created by another admin”, only the admin who added this worker can change it." },
        ],
      },
      {
        id: "employee-status",
        title: "Move a worker to the next step",
        summary: "For example Medical Done or Visa Issued.",
        keywords: ["status", "assign status", "stage", "pipeline", "progress"],
        where: "Employees → pencil → Status",
        steps: [
          "Open the worker with the pencil button.",
          "Under Status click + Assign Status (1).",
          "Pick the new step and click Assign.",
          "All steps the worker passed show as coloured labels. The last one is the current step.",
        ],
        shots: [
          { id: "employee-status", caption: "+ Assign Status." },
          { id: "employee-status-modal", caption: "Pick the step (1) and click Assign (2)." },
        ],
      },
      {
        id: "employee-documents",
        title: "Add and see papers",
        summary: "Keep scans of passport, COC, visa, medical, contract and more.",
        keywords: ["documents", "files", "upload", "scan", "yellow card", "tasheer", "folder"],
        where: "Worker form → Documents, or the folder button",
        steps: [
          "Under Documents pick the type (1), write a short note, pick the file (2) and click Add (3).",
          "The files are saved when you click Create Worker or Save Changes.",
          "To see them later, click the folder button on the row. Click a file to open it. You can download or delete it.",
        ],
        shots: [
          { id: "employee-documents", caption: "Adding a paper." },
          { id: "employee-files", caption: "The worker's files." },
        ],
        notes: [{ type: "tip", text: "You can add pictures, PDF and Word files." }],
      },
      {
        id: "employee-cv",
        title: "Make a CV and send it to a partner",
        summary: "Pick the partner and colour, then download or share.",
        keywords: ["cv", "resume", "download cv", "link partner", "share", "revoke", "header"],
        where: "Employees → PDF button",
        steps: [
          "Click the PDF button on the row.",
          "Pick the Partner (1). Their logo goes at the top of the CV.",
          "Pick a colour (2). Tick Include Passport (3) to add the passport page.",
          "Click Download CV (4) to save it.",
          "Click Link Partner (5) to share it. The partner can now see this worker.",
          "After sharing, use the switch to stop or allow the partner's access.",
        ],
        shots: [
          { id: "employee-cv", caption: "CV choices and buttons." },
          { id: "employee-cv-shared", caption: "A shared CV. Use the switch (1) to stop or allow access." },
        ],
        notes: [{ type: "warning", text: "The partner needs a CV header picture. Add it in Users → edit the partner." }],
      },
      {
        id: "employee-visa",
        title: "Get the visa form",
        summary: "The visa form fills in by itself.",
        keywords: ["visa application", "download visa", "application form", "share whatsapp"],
        where: "Employees → passport button",
        steps: [
          "Click the passport button on the row.",
          "Check the filled form.",
          "Click Download to save it, Share to send it, or Cancel.",
          "If something is missing, the worker form opens and shows a red ! next to it. Fill it and try again.",
        ],
        shots: [{ id: "employee-visa", caption: "The visa form. Download (1) or Share (2)." }],
      },
      {
        id: "employee-transaction",
        title: "Add a payment for a worker",
        summary: "Open the money form with the worker already chosen.",
        keywords: ["transaction", "payment", "fee", "wallet"],
        access: { paths: ["/admin/finances"] },
        where: "Employees → wallet button",
        steps: [
          "Click the wallet button on the row.",
          "The money form opens with the worker chosen.",
          "Fill it and click Save Transaction. See Finance.",
        ],
      },
      {
        id: "employee-archive",
        title: "Archive, bring back or delete",
        summary: "Hide workers who left, bring them back or remove them.",
        keywords: ["archive", "restore", "delete", "remove employee", "archived"],
        where: "Employees → row buttons",
        steps: [
          "Click the archive button and confirm. The worker is hidden from the active list.",
          "To see hidden workers, pick Archived (1) in the boxes at the top.",
          "Click the round arrow (2) to bring a worker back.",
          "Admins can delete a worker for good with the bin button (3).",
        ],
        shots: [{ id: "employees-archived", caption: "Archived (1), bring back (2) and delete (3)." }],
        notes: [{ type: "warning", text: "Delete removes the worker and all their information forever. Only admins can do it." }],
      },
      {
        id: "employees-bulk",
        title: "Pick many workers at once",
        summary: "Make an invoice, autofill, print insurance or write a letter.",
        keywords: ["bulk", "select", "multiple", "create invoice", "autofill", "insurance", "letter", "double click"],
        where: "Employees → double-click a row",
        steps: [
          "Double-click a row. Tick boxes appear (5).",
          "Tick the workers you want. The bar shows how many you picked.",
          "Create Invoice (1) – make a bill for them.",
          "Autofill (2) – send them to the Autofill page.",
          "Print Insurance (3) – print their insurance list.",
          "Create Letter – shows when you pick only 1 worker.",
          "Cancel (4) – stop picking.",
        ],
        shots: [{ id: "employees-bulk", caption: "The bar after picking workers." }],
        notes: [
          { type: "tip", text: "The tick box at the top of the table picks every worker on the page." },
          { type: "warning", text: "A worker on an unpaid invoice cannot go on a new invoice." },
        ],
      },
      {
        id: "employees-report",
        title: "Print a partner's worker list",
        summary: "Print all workers with a contract for one partner.",
        keywords: ["report", "print report", "partner report"],
        where: "Employees → pick a partner → Print Report",
        steps: [
          "Pick a partner in the Partner box (1).",
          "Click Print Report (2).",
          "If you picked some workers, only they are printed. If not, the whole list is printed.",
        ],
        shots: [{ id: "employees-report", caption: "Print Report shows after you pick a partner." }],
      },
    ],
  },

  {
    id: "partner-employees",
    group: "employees",
    title: "Active Employees (Partner)",
    icon: "bi-people",
    summary: "See the workers shared with you and download their CVs.",
    access: { paths: ["/partner/active-employees"] },
    topics: [
      {
        id: "partner-list",
        title: "Your worker list",
        summary: "Workers the agency shared with you.",
        keywords: ["partner", "employees", "shared cv", "list"],
        where: "Menu → Active Employees",
        steps: [
          "Click Active Employees in the menu.",
          "Search by name, phone, passport, labour ID or agent. You can also pick a status.",
          "Click the PDF button (1) to open the worker's CV.",
        ],
        shots: [{ id: "partner-employees", caption: "Your worker list." }],
      },
      {
        id: "partner-cv",
        title: "Download a CV",
        summary: "Save the CV with your logo.",
        keywords: ["cv", "download", "pdf"],
        where: "Active Employees → PDF button",
        steps: [
          "Open the CV with the PDF button.",
          "Check the CV. Your logo is at the top.",
          "Click Download CV (1). The PDF is saved on your computer.",
        ],
        shots: [{ id: "partner-cv", caption: "Click Download CV (1)." }],
        notes: [{ type: "tip", text: "If you cannot open a CV, ask the agency to share it." }],
      },
    ],
  },

  {
    id: "autofill",
    group: "employees",
    title: "Autofill",
    icon: "bi-ui-checks",
    summary: "Fill Musaned, Wafid, Tasheer or Nyala forms for you, using the Chrome extension.",
    access: { paths: ["/admin/autofill"] },
    topics: [
      {
        id: "autofill-use",
        title: "Fill online forms for you",
        summary: "Pick workers and open the website.",
        keywords: ["autofill", "musaned", "wafid", "tasheer", "nyala", "insurance", "chrome extension", "queue", "export tasheer"],
        where: "Employees → pick workers → Autofill",
        steps: [
          "In Employees, double-click a row, tick the workers and click Autofill.",
          "The page shows how many workers you picked (1). Click it to change them.",
          "Click a website card (2), for example Musaned. The website opens and the data is ready.",
          "Export Tasheer (3) saves an Excel file for Tasheer.",
          "Reset (4) removes the picked workers.",
        ],
        shots: [{ id: "autofill", caption: "The Autofill page." }],
        notes: [{ type: "warning", text: "Autofill only works in Google Chrome with the agency's Autofill extension." }],
      },
    ],
  },

  {
    id: "tickets",
    group: "employees",
    title: "Tickets",
    icon: "bi-ticket-detailed",
    summary: "Compare flight prices from travel agencies.",
    access: { paths: ["/admin/tickets"] },
    topics: [
      {
        id: "tickets-search",
        title: "Find the cheapest ticket",
        summary: "Pick a city, a date and how many days to check.",
        keywords: ["ticket", "flight", "price", "airline", "destination", "jeddah", "riyadh", "kuwait", "dubai"],
        where: "Menu → Tickets",
        steps: [
          "Pick the city you fly to (1), for example Riyadh.",
          "Pick the date (2).",
          "Pick how many days to check (3): 1, 3, 7 or 15.",
          "The search starts by itself. Best Prices shows the cheapest. All Results shows every ticket.",
          "Click Cancel (4) to stop.",
        ],
        shots: [{ id: "tickets", caption: "Ticket search." }],
        notes: [{ type: "tip", text: "Checking 15 days can take 10–15 minutes. Try 1 day first." }],
      },
    ],
  },

  {
    id: "letter",
    group: "employees",
    title: "Letter",
    icon: "bi-file-earmark-text",
    summary: "Write and print official letters.",
    access: { paths: ["/admin/letter"] },
    topics: [
      {
        id: "letter-write",
        title: "Write a letter",
        summary: "Type the letter and make it look nice.",
        keywords: ["letter", "write", "format", "bold", "font", "rtl", "subject", "to"],
        where: "Menu → Letter, or Employees → pick 1 worker → Create Letter",
        steps: [
          "Open Letter from the menu. Or pick 1 worker in Employees and click Create Letter. Their details are then ready in the Toolkit.",
          "Click To or Subject in the letter. Pick a choice from the list or type your own.",
          "Type the letter text.",
          "Use the buttons at the top (1) for size, bold, lines, lists and right-to-left text.",
        ],
        shots: [{ id: "letter", caption: "The letter with its buttons (1) and Toolkit (2)." }],
      },
      {
        id: "letter-toolkit",
        title: "Save, copy, add pictures and print",
        summary: "The Toolkit on the right of the letter.",
        keywords: ["cache", "save draft", "copy", "screenshots", "attach scan", "passport scan", "print"],
        where: "Letter → Toolkit",
        steps: [
          "Save to Cache keeps your letter in this browser for later. Remove from Cache deletes it.",
          "Click a detail like Name or Passport No. to copy it.",
          "Screenshots: add pictures to print after the letter.",
          "Attach Scan adds the worker's passport scan.",
          "Click Print. You can also save it as PDF.",
        ],
      },
      {
        id: "letter-stamp",
        title: "Add the stamp and signature",
        summary: "Put the office stamp and signature on the letter.",
        keywords: ["stamp", "signature", "seal"],
        access: { roles: [ADMIN] },
        where: "Letter → Toolkit → Stamp & Signature",
        steps: [
          "Click Attach Stamp or Attach Signature.",
          "Click on the letter where it should go, or click Bottom center (default).",
          "Drag it to move it. Drag the blue corner to make it bigger or smaller. Click × to remove it.",
        ],
        notes: [{ type: "tip", text: "Upload the stamp and signature first in Settings." }],
      },
    ],
  },

  {
    id: "local-agents",
    group: "employees",
    title: "Local Agents",
    icon: "bi-person-video",
    summary: "The agents you can pick on the worker form.",
    access: { paths: ["/admin/meta-data/local-agents"] },
    topics: [
      {
        id: "agents-manage",
        title: "Add, rename and delete agents",
        summary: "Keep the agent list right.",
        keywords: ["agent", "local agent", "broker", "add agent", "rename"],
        where: "Menu → Local Agents",
        steps: [
          "Click + Agent (1). Type the name and phone. Save.",
          "Use the search box (2) to find an agent.",
          "Click the rename button (3), type the new name and press Enter. Press Esc to stop.",
          "Click the bin button to delete an agent.",
        ],
        shots: [{ id: "agents", caption: "The Local Agents page." }],
        notes: [{ type: "warning", text: "Two agents cannot have the same phone number." }],
      },
    ],
  },

  {
    id: "status",
    group: "employees",
    title: "Status",
    icon: "bi-database-add",
    summary: "The list of steps a worker goes through.",
    access: { paths: ["/admin/meta-data/employee-status"] },
    topics: [
      {
        id: "status-manage",
        title: "Manage worker steps",
        summary: "Add, rename or delete steps.",
        keywords: ["status", "stage", "pipeline", "rename status"],
        where: "Menu → Status",
        steps: [
          "Click + Status (1). Type the name, for example Medical Done. Save.",
          "Click the rename button (2) to change a name.",
          "Click the bin button to delete a step.",
          "These steps show in the worker form and on the Dashboard.",
        ],
        shots: [{ id: "status", caption: "The Status page." }],
      },
    ],
  },

  // --------------------------------------------------------------- FINANCE
  {
    id: "finance",
    group: "finance",
    title: "Finance",
    icon: "bi-wallet-fill",
    summary: "Write down money in and out, print receipts and close the books.",
    access: { paths: ["/admin/finances"] },
    topics: [
      {
        id: "finance-list",
        title: "Money list",
        summary: "All money in and out for now.",
        keywords: ["finance", "transactions", "income", "expense", "list"],
        where: "Menu → Finance",
        steps: [
          "Click Finance in the menu.",
          "New Transaction (1) adds money in or out. Periods (2) shows past and current books.",
          "Use the boxes (3) to pick a type or dates.",
          "Green labels are money in. Red labels are money out.",
          "Use the row buttons (4) to see, change or delete.",
        ],
        shots: [{ id: "finance-list", caption: "The Finance page." }],
      },
      {
        id: "finance-new",
        title: "Add money in or out",
        summary: "Income, costs, salary, commission or VAT.",
        keywords: ["new transaction", "record", "amount", "category", "receipt", "reference", "vat", "salary", "commission"],
        where: "Finance → New Transaction",
        steps: [
          "Click New Transaction.",
          "Type the Amount.",
          "Pick the Category. Income, Office Income and Partner Commission are money in. The others are money out.",
          "Pick the Transaction Date (today or before).",
          "Type the Reference (receipt number) and a short Description.",
          "Click Save Transaction (1).",
        ],
        shots: [{ id: "finance-new", caption: "The money form. Click Save Transaction (1)." }],
      },
      {
        id: "finance-receipt",
        title: "See and print a receipt",
        summary: "All details of one payment.",
        keywords: ["receipt", "print receipt", "details", "view invoice"],
        where: "Finance → eye button",
        steps: [
          "Click the eye button on a row.",
          "You see the amount, type, date, number and who added it.",
          "Click Print Receipt (1). If it came from an invoice, View Invoice opens the invoice.",
        ],
        shots: [{ id: "finance-receipt", caption: "A receipt with Print Receipt (1)." }],
      },
      {
        id: "finance-periods",
        title: "Book periods",
        summary: "The current books and the closed ones.",
        keywords: ["period", "financial period", "closed period", "history", "net profit"],
        where: "Finance → Periods",
        steps: [
          "Click Periods.",
          "The green card is the current period. View Transactions (1) shows its money list.",
          "Close Current Period (2) is for admins (see below).",
          "The table shows closed periods and their profit.",
          "Click the eye (3) on a closed period to see it. Summary shows totals. Generate Report prints them.",
        ],
        shots: [{ id: "finance-periods", caption: "The Periods page." }],
      },
      {
        id: "finance-close",
        title: "Close the books",
        summary: "Save the totals after a check and start new books.",
        keywords: ["close period", "audit", "end of month", "closing note"],
        access: { roles: [ADMIN] },
        where: "Finance → Periods → Close Current Period",
        steps: [
          "Click Close Current Period.",
          "Write a short note (1).",
          "Click Confirm & Close (2). The totals are saved and new books start.",
        ],
        shots: [{ id: "finance-close", caption: "Closing the books." }],
        notes: [
          { type: "warning", text: "You cannot change money rows in closed books. Deleting closed books also deletes all their rows." },
        ],
      },
    ],
  },

  {
    id: "invoices",
    group: "finance",
    title: "Invoices",
    icon: "bi-receipt",
    summary: "Send bills to partners and record their payments.",
    access: { paths: ["/admin/invoices"] },
    topics: [
      {
        id: "invoice-create",
        title: "Make an invoice",
        summary: "Start from the worker list and save a draft.",
        keywords: ["invoice", "create invoice", "bill", "draft", "customer", "amount"],
        access: { paths: ["/admin/employees"] },
        where: "Employees → pick workers → Create Invoice",
        steps: [
          "In Employees, double-click a row, tick the workers and click Create Invoice.",
          "Pick the Customer (partner) (1) and the date.",
          "Type the amount for each worker (2). You can also pick an agent for each row.",
          "Add Employee (3) adds or removes workers.",
          "Check the Total and click Save Draft (4).",
        ],
        shots: [{ id: "invoice-form", caption: "The invoice form." }],
        notes: [{ type: "warning", text: "A worker can be on only one unpaid invoice." }],
      },
      {
        id: "invoice-list",
        title: "Invoice list",
        summary: "Find invoices and see if they are paid.",
        keywords: ["invoices", "status", "draft", "issued", "partially paid", "paid", "cancelled", "search invoice"],
        where: "Menu → Invoices",
        steps: [
          "Search by invoice number or partner, or pick a status and dates (1).",
          "Draft = not sent yet. Issued = sent. Partially Paid = some money came. Paid = all paid. Cancelled = stopped.",
          "Click the eye button (2) to open an invoice. Drafts can also be changed or deleted.",
        ],
        shots: [{ id: "invoices-list", caption: "Filters (1) and the open button (2)." }],
      },
      {
        id: "invoice-issue-pay",
        title: "Send, get paid or cancel",
        summary: "Move an invoice from draft to paid.",
        keywords: ["issue invoice", "record payment", "cancel invoice", "payment", "bank transfer"],
        where: "Invoices → eye button",
        steps: [
          "Open the invoice.",
          "Issue Invoice makes it final. The amounts cannot change after this.",
          "Record Payment (1): type the amount that came in and click Save Transaction.",
          "Cancel Invoice stops it. You cannot undo this.",
          "Print Invoice (2) opens the print page.",
        ],
        shots: [
          { id: "invoice-detail", caption: "An invoice and its buttons." },
          { id: "invoice-payment", caption: "Type the amount (1) and click Save Transaction (2)." },
        ],
        notes: [{ type: "tip", text: "Payments are added to Finance by themselves." }],
      },
      {
        id: "invoice-print",
        title: "Print an invoice",
        summary: "Set the file name, stamp and bank details.",
        keywords: ["print invoice", "pdf", "bank information", "stamp"],
        where: "Invoice → Print Invoice",
        steps: [
          "Change the File Name if you want.",
          "Move the stamp and signature, or click Reset positions.",
          "Tick Include bank information to show the bank details.",
          "Click Print.",
        ],
        shots: [{ id: "invoice-print", caption: "The print page." }],
      },
    ],
  },

  // --------------------------------------------------------- COMMUNICATION
  {
    id: "notifications",
    group: "communication",
    title: "Notifications",
    icon: "bi-bell",
    summary: "Read your messages and send messages.",
    access: { paths: ["/admin/notifications", "/partner/notifications"] },
    topics: [
      {
        id: "notifications-read",
        title: "Read messages",
        summary: "Open a message.",
        keywords: ["inbox", "message", "read", "notification"],
        where: "Menu → Notifications, or the bell",
        steps: [
          "Click Notifications in the menu, or the bell.",
          "Click a message in the Inbox (1). It opens on the right (2).",
          "On a phone, tap the back arrow to go back.",
        ],
        shots: [{ id: "notifications-inbox", caption: "Inbox and an open message." }],
      },
      {
        id: "notifications-send",
        title: "Send a message",
        summary: "To one person or many people.",
        keywords: ["send alert", "message", "broadcast", "notify"],
        access: { roles: [ADMIN, STAFF] },
        where: "Notifications → Send Alert",
        steps: [
          "Click Send Alert.",
          "Pick who gets it: Partner or Staff (1).",
          "Type part of the name and click the person (2).",
          "Write the message (3) and click Send Alert.",
        ],
        shots: [{ id: "notifications-send", caption: "Writing a message." }],
        notes: [{ type: "tip", text: "To message many users, use the bell button or pick many rows in Users." }],
      },
      {
        id: "admin-bell",
        title: "The bell",
        summary: "See when staff log in or change things.",
        keywords: ["bell", "real time", "live", "mark all as read", "alerts"],
        access: { roles: [ADMIN] },
        where: "Top of the page → bell",
        steps: [
          "The red number shows new alerts.",
          "Click the bell (1) to see the latest ones.",
          "Click an alert to see all its details.",
          "Click Mark all as read (2), or View all to see everything.",
        ],
        shots: [{ id: "admin-bell", caption: "The bell's list." }],
      },
    ],
  },

  {
    id: "website-messages",
    group: "communication",
    title: "Website Messages",
    icon: "bi-envelope-paper-heart",
    summary: "Read and answer the messages visitors send from the website’s contact form.",
    access: { paths: ["/admin/messages"] },
    topics: [
      {
        id: "messages-read",
        title: "Read a website message",
        summary: "Open the messages people send from the public website.",
        keywords: ["messages", "contact form", "inquiry", "website", "inbox", "unread", "visitor"],
        where: "Menu → Messages",
        steps: [
          "Click Messages in the menu (1). The red number shows how many messages are not read yet.",
          "Click a message in the list (2).",
          "It opens on the right (3): the sender’s name, phone, email and the message.",
          "Opening a message marks it as read, so the red number goes down.",
        ],
        shots: [{ id: "messages-inbox", caption: "Messages in the menu (1), a message in the list (2) and the open message (3)." }],
        notes: [
          { type: "tip", text: "New messages appear at the top by themselves, with a short alert — you do not need to refresh the page." },
          { type: "tip", text: "Messages written in Arabic or Amharic show the right way round." },
        ],
      },
      {
        id: "messages-find",
        title: "Find a message",
        summary: "Search, show only unread or starred messages.",
        keywords: ["search", "filter", "unread", "starred", "find message"],
        where: "Messages → top of the list",
        steps: [
          "Type a name, phone number, email or a word from the message in the search box (1).",
          "Click All, Unread or Starred (2) to show only those messages.",
          "The number cards (3) show the totals. Click Unread or Starred on a card to filter too.",
          "Click a message, then use the ↑ and ↓ keys to move through the list.",
        ],
        shots: [{ id: "messages-filters", caption: "Search box (1), All / Unread / Starred (2) and the number cards (3)." }],
      },
      {
        id: "messages-reply",
        title: "Answer the sender",
        summary: "Reply by email, call, or chat on WhatsApp.",
        keywords: ["reply", "email", "gmail", "outlook", "call", "whatsapp", "answer"],
        where: "Open message → bottom buttons",
        steps: [
          "Click Reply by email (1). A small list opens (2).",
          "Pick Default mail app to use the mail program on this computer or phone.",
          "Or pick Gmail or Outlook on the web — a new tab opens with the answer ready to write.",
          "The sender’s address, the subject and their message are filled in for you. Write your answer and send it.",
          "Click Copy email address if you want to use another mail program.",
          "To phone the sender click Call. To chat click WhatsApp.",
        ],
        shots: [{ id: "messages-reply", caption: "Reply by email (1) and the ways to reply (2)." }],
        notes: [
          { type: "tip", text: "If Default mail app does nothing, this computer has no mail program set up. Use Gmail or Outlook on the web instead." },
          { type: "tip", text: "Reply by email only shows when the sender typed an email. Phone and WhatsApp are always there." },
        ],
      },
      {
        id: "messages-organize",
        title: "Star, mark as unread or delete",
        summary: "Keep the inbox tidy.",
        keywords: ["star", "unread", "delete", "mark all read", "emailed to inbox", "dashboard only"],
        where: "Open message → top right buttons",
        steps: [
          "Click the star (1) to keep an important message in Starred.",
          "Click the envelope (2) to mark the message as unread again.",
          "Click the bin (3) to delete it. Click Delete to confirm.",
          "The green label Emailed to inbox (4) means a copy was also sent to the agency email. Dashboard only means it was not — this page is the only copy.",
          "Click Mark all read (5) to mark every message as read.",
        ],
        shots: [{ id: "messages-actions", caption: "Star (1), unread (2), delete (3), email label (4) and Mark all read (5)." }],
        notes: [
          { type: "warning", text: "A deleted message cannot come back." },
        ],
      },
      {
        id: "messages-mobile",
        title: "Messages on a phone",
        summary: "The list and the message take turns on a small screen.",
        keywords: ["phone", "mobile", "back", "inbox"],
        where: "Menu → Messages (phone)",
        steps: [
          "Tap a message in the list to open it.",
          "Tap ← Inbox (1) to go back to the list.",
        ],
        shots: [{ id: "messages-mobile", caption: "An open message on a phone. Tap Inbox (1) to go back.", mobile: true }],
      },
    ],
  },

  {
    id: "complaints",
    group: "communication",
    title: "Complaints",
    icon: "bi-exclamation-triangle",
    summary: "Write down problems of workers abroad and follow them up.",
    access: { paths: ["/admin/complaints"] },
    topics: [
      {
        id: "complaints-list",
        title: "Complaint list",
        summary: "All complaints and where they are.",
        keywords: ["complaint", "list", "open", "investigating", "resolved"],
        where: "Menu → Complaints",
        steps: [
          "Log Complaint (1) adds a new complaint.",
          "Search by worker or employer name, or pick a status (2).",
          "Use the row buttons (3) to see, change or delete.",
        ],
        shots: [{ id: "complaints-list", caption: "The Complaints page." }],
      },
      {
        id: "complaint-create",
        title: "Add a complaint",
        summary: "Who, what happened, who called and what you did.",
        keywords: ["log complaint", "new complaint", "complainant", "resolution", "employer"],
        where: "Complaints → Log Complaint",
        steps: [
          "Worker: start typing the name and pick the worker, or type a new name.",
          "Complaint: write what happened. This is needed.",
          "Complainant: name and phone of the person who told you. Click + Add Complainant for more people.",
          "Employer: name, phone and address.",
          "Resolution: how you tried to help (phone, email or social media). Click + Add Resolution Attempt for more.",
          "Pick Date Received and click Submit Complaint.",
        ],
        shots: [{ id: "complaint-form", caption: "The complaint form." }],
      },
      {
        id: "complaint-follow",
        title: "Follow up and close",
        summary: "Change the status and write the result.",
        keywords: ["status", "investigating", "resolved", "outcome", "print complaint"],
        where: "Complaints → pencil or eye button",
        steps: [
          "Click the eye button to read the whole complaint. You can print it.",
          "Click the pencil button. Change Status to Investigating or Resolved.",
          "When it is finished, write the result in Complaint Outcome. Click Update Complaint.",
          "Only admins can delete a complaint.",
        ],
        shots: [{ id: "complaint-detail", caption: "A complaint's details." }],
      },
    ],
  },

  {
    id: "external-links",
    group: "communication",
    title: "External Links",
    icon: "bi-link-45deg",
    summary: "Quick links to government and partner websites.",
    access: { paths: ["/admin/external-links"] },
    topics: [
      {
        id: "external-open",
        title: "Open a website",
        summary: "EOW, Musaned, Wafid, LMIS, Tasheer, Visa Mofa, Easy Enjaz, Telebirr and Tiketing.",
        keywords: ["external links", "musaned", "wafid", "lmis", "eow", "tasheer", "mofa", "enjaz", "telebirr", "ticketing"],
        where: "Menu → External Links",
        steps: ["Click External Links.", "Click a card. The website opens in a new tab."],
        shots: [{ id: "external-links", caption: "The External Links page." }],
      },
    ],
  },

  // ---------------------------------------------------------------- ADMIN
  {
    id: "users",
    group: "admin",
    title: "Users",
    icon: "bi-people",
    summary: "Make accounts for staff and partners and choose what staff can do.",
    access: { paths: ["/admin/users"] },
    topics: [
      {
        id: "users-list",
        title: "User list",
        summary: "Find staff and partners.",
        keywords: ["users", "staff", "partner", "accounts", "list"],
        where: "Menu → Users",
        steps: [
          "Create User (1) makes a new account.",
          "Search by name, email or phone, or pick a role and status (2).",
          "Row buttons (3): change, message, archive, bring back, delete and add payment.",
        ],
        shots: [{ id: "users-list", caption: "The Users page." }],
      },
      {
        id: "users-create-staff",
        title: "Make a staff account",
        summary: "Give staff only the pages they need.",
        keywords: ["create user", "staff", "permissions", "manage users", "manage employees", "manage finance", "manage analytics", "manage complaints"],
        where: "Users → Create User → Role: Staff",
        steps: [
          "Click Create User.",
          "Type Full Name (letters only), Phone Number and Email.",
          "Pick Role: Staff.",
          "Tick what they can use (1): Users, Employees, Finance, Dashboard (Analytics) and Complaints. Check All ticks all.",
          "Click Create User (2).",
        ],
        shots: [{ id: "users-create-staff", caption: "A staff account and what they can use." }],
        notes: [
          { type: "tip", text: "Staff only see the pages you tick. This manual follows the same rule." },
          { type: "warning", text: "Tick at least one." },
        ],
      },
      {
        id: "users-create-partner",
        title: "Make a partner account",
        summary: "Add a foreign office and its CV logo.",
        keywords: ["partner", "create partner", "cv header", "country", "office"],
        where: "Users → Create User → Role: Partner",
        steps: [
          "Pick Role: Partner.",
          "Pick the Country (1).",
          "Pick the CV Header picture (2). It is needed. CV Header (Page 2) is optional.",
          "Click Create User.",
        ],
        shots: [{ id: "users-create-partner", caption: "Partner account boxes." }],
        notes: [{ type: "tip", text: "Pictures must be JPG, PNG or WEBP and smaller than 5 MB." }],
      },
      {
        id: "users-edit",
        title: "Change, archive or delete a user",
        summary: "Change details or stop an account.",
        keywords: ["edit user", "archive user", "restore", "delete user", "inactive", "deactivate"],
        where: "Users → row buttons",
        steps: [
          "Pencil – change details or what they can use. Click Update User.",
          "Archive – the user cannot log in. Pick Inactive at the top to see them, then bring them back with the round arrow.",
          "Bin – delete the account.",
        ],
        notes: [{ type: "warning", text: "You cannot archive or delete your own account." }],
      },
      {
        id: "users-notify",
        title: "Message one or many users",
        summary: "Send a message from the user list.",
        keywords: ["notify", "alert", "bulk", "message users"],
        where: "Users → bell button, or double-click a row",
        steps: [
          "Click the bell button on a row to message one person.",
          "For many people: double-click a row, tick the users and click Alert (1).",
          "Write the message and send it.",
        ],
        shots: [{ id: "users-bulk", caption: "Picking many users." }],
      },
      {
        id: "users-transaction",
        title: "Add a payment for a user",
        summary: "For example a partner commission.",
        keywords: ["transaction", "partner commission", "wallet"],
        access: { paths: ["/admin/finances"] },
        where: "Users → wallet button",
        steps: [
          "Click the wallet button on the row.",
          "The money form opens with the user chosen. Fill it and save.",
        ],
      },
    ],
  },

  {
    id: "public-content",
    group: "admin",
    title: "Public Content",
    icon: "bi-layout-text-sidebar-reverse",
    summary: "Change the address, photos and social links on the public website.",
    access: { paths: ["/admin/content"] },
    topics: [
      {
        id: "content-home",
        title: "Website content",
        summary: "Pick Location, Gallery or Social Media.",
        keywords: ["public content", "website", "landing page"],
        where: "Menu → Public Content",
        steps: ["Click Public Content.", "Click Location, Gallery or Social Media."],
        shots: [{ id: "content", caption: "The Public Content page." }],
      },
      {
        id: "public-website",
        title: "Your public website",
        summary: "Languages, the WhatsApp button and the contact form.",
        keywords: ["website", "language", "amharic", "arabic", "english", "whatsapp", "contact form", "public site"],
        where: "Home page of the website (Menu → Home)",
        steps: [
          "Visitors can read the website in English, Amharic or Arabic. They click the globe button (1) and pick a language. Arabic shows from right to left.",
          "The green WhatsApp button (2) opens a chat with the agency number +251 911 368 146. It appears after the visitor scrolls down a little.",
          "When a visitor sends the contact form, the message goes to Messages in the menu (admins).",
          "The phone number, email, address and social links on the website come from Location and Social Media on this page.",
        ],
        shots: [{ id: "public-site", caption: "The language button (1) and the WhatsApp button (2) on the website." }],
        notes: [
          { type: "tip", text: "The website remembers the language each visitor picked." },
        ],
      },
      {
        id: "content-location",
        title: "Office address on the map",
        summary: "Set where the office is.",
        keywords: ["location", "map", "latitude", "longitude", "address"],
        where: "Public Content → Location",
        steps: [
          "Type the Location Name, Latitude, Longitude and Address.",
          "Click Create Location or Update Location. Delete removes it.",
        ],
        shots: [{ id: "content-location", caption: "The location form." }],
        notes: [{ type: "tip", text: "Copy latitude and longitude from Google Maps: right-click the office on the map." }],
      },
      {
        id: "content-gallery",
        title: "Photos",
        summary: "Add, change and remove website photos.",
        keywords: ["gallery", "photos", "images", "upload", "delete all"],
        where: "Public Content → Gallery",
        steps: [
          "Click Add Gallery (1). Type a title, a short text if you want, and pick a picture. Click Create Item.",
          "Use the arrows to move between photos. Use the pencil or bin to change or delete one.",
          "Delete All (2) removes all photos.",
        ],
        shots: [{ id: "content-gallery", caption: "The Gallery page." }],
      },
      {
        id: "content-social",
        title: "Social links and contacts",
        summary: "Facebook, Telegram, WhatsApp, phone and email.",
        keywords: ["social media", "facebook", "instagram", "telegram", "tiktok", "whatsapp", "contact"],
        where: "Public Content → Social Media",
        steps: [
          "Fill at least one box.",
          "Click Create or Update. Delete removes all of them.",
        ],
        shots: [{ id: "content-social", caption: "The Social Media form." }],
      },
    ],
  },

  {
    id: "activities",
    group: "admin",
    title: "Activities & Audit Log",
    icon: "bi-journal-text",
    summary: "See who logged in and what staff changed.",
    access: { paths: ["/admin/activities"] },
    topics: [
      {
        id: "activities-login",
        title: "Logins",
        summary: "Every login, good or failed.",
        keywords: ["login activity", "failed login", "ip address", "device", "security"],
        where: "Menu → Activities → Login Activity",
        steps: [
          "Click Activities. Login Activity (1) opens.",
          "Pick a user, Success or Failed, or dates (2).",
          "Each row shows who, from where, which device, when, and if it worked.",
        ],
        shots: [{ id: "activities-login", caption: "Logins." }],
        notes: [{ type: "warning", text: "Many failed logins on one account can mean someone is guessing the password." }],
      },
      {
        id: "activities-audit",
        title: "Changes by staff",
        summary: "What each staff member added, changed or deleted.",
        keywords: ["audit log", "history", "changes", "who changed", "track"],
        where: "Activities → Audit Log",
        steps: [
          "Click Audit Log (1).",
          "Search, or pick a staff member, an action and dates (2).",
          "Click the eye button to see before and after.",
        ],
        shots: [
          { id: "activities-audit", caption: "Changes by staff." },
          { id: "activity-detail", caption: "Details of one change." },
        ],
      },
      {
        id: "activities-delete",
        title: "Delete old rows",
        summary: "Remove one or many rows.",
        keywords: ["delete", "bulk delete", "clean up"],
        where: "Activities → bin button or double-click a row",
        steps: [
          "Click the bin button to delete one row.",
          "For many: double-click a row, tick the rows and click Delete Selected.",
        ],
      },
    ],
  },

  {
    id: "settings",
    group: "admin",
    title: "Settings & Profile",
    icon: "bi-gear",
    summary: "Your details, your password and the office stamp and signature.",
    access: { paths: ["/admin/settings", "/partner/settings"] },
    topics: [
      {
        id: "settings-profile",
        title: "Change your details",
        summary: "Photo, name, email and phone.",
        keywords: ["profile", "photo", "name", "email", "phone", "my profile"],
        where: "Menu → Settings",
        steps: [
          "Click Settings.",
          "Pick a Profile Image if you want a photo.",
          "Change your name, email or phone.",
          "Click Save Changes (1).",
        ],
        shots: [{ id: "settings-profile", caption: "My Profile." }],
      },
      {
        id: "settings-password",
        title: "Change your password",
        summary: "Use at least 8 characters.",
        keywords: ["change password", "new password", "security"],
        where: "Settings → Change Your Password",
        steps: [
          "Type your Old Password.",
          "Type the New Password (8 characters or more). Type it again in Confirm Password.",
          "Click Save Changes.",
        ],
        shots: [{ id: "settings-password", caption: "Change Your Password." }],
      },
      {
        id: "settings-organization",
        title: "Office stamp and signature",
        summary: "Pictures used on letters and invoices.",
        keywords: ["stamp", "signature", "organization settings", "upload"],
        access: { roles: [ADMIN] },
        where: "Settings → Organization Settings",
        steps: [
          "Click Upload (or Replace) under Stamp or Signature. Pick a PNG, JPEG or WEBP picture under 5 MB.",
          "Click the bin to remove it.",
        ],
        shots: [{ id: "settings-organization", caption: "Organization Settings." }],
        notes: [{ type: "tip", text: "A PNG with no background looks best when printed." }],
      },
    ],
  },

  // ----------------------------------------------------------------- HELP
  {
    id: "workflows",
    group: "help",
    title: "Common Workflows",
    icon: "bi-diagram-3",
    summary: "Step-by-step guides for everyday jobs.",
    access: {},
    topics: [
      {
        id: "wf-register-to-departure",
        title: "From new worker to travel",
        summary: "The usual path of a new worker.",
        keywords: ["workflow", "process", "departure", "register", "visa", "ticket"],
        access: { paths: ["/admin/employees"] },
        steps: [
          "Employees → Add Employee. Upload the passport, fill the main details, pick Registered and click Create Worker.",
          "When papers arrive, open the worker and fill COC, Medical, Emergency Contact and Agent. Add scans in Documents.",
          "After each step, click + Assign Status (COC Passed, Medical Done, Contract Signed…).",
          "Open the CV, pick the partner and click Link Partner.",
          "When the contract is signed, fill Contract and Visa. Download the visa form.",
          "Fill Travel with the ticket and dates. Give the status Departed.",
        ],
        flow: ["Add worker", "Papers", "Steps", "Share CV", "Visa", "Travel"],
      },
      {
        id: "wf-website-inquiry",
        title: "Answer a website inquiry",
        summary: "From a visitor’s message to a reply.",
        keywords: ["workflow", "website", "inquiry", "contact form", "reply", "messages"],
        access: { paths: ["/admin/messages"] },
        steps: [
          "A red number appears next to Messages in the menu.",
          "Open Messages and click the new message to read it.",
          "Answer with Reply by email, Call or WhatsApp.",
          "Star it if you need to follow up later, or delete it when you are done.",
        ],
        flow: ["New message", "Read", "Reply", "Star or delete"],
      },
      {
        id: "wf-invoice",
        title: "Bill a partner and get paid",
        summary: "Make the invoice, send it and record the payment.",
        keywords: ["workflow", "invoice", "payment", "billing"],
        access: { allPaths: ["/admin/employees", "/admin/invoices"] },
        steps: [
          "Employees → double-click a row, tick the workers, click Create Invoice.",
          "Pick the partner, type the amounts, click Save Draft.",
          "Open the invoice and click Issue Invoice.",
          "When money comes, click Record Payment.",
          "Open Finance. The payment is there as money in.",
        ],
        flow: ["Pick workers", "Save draft", "Issue", "Record payment"],
      },
      {
        id: "wf-share-cv",
        title: "Send a CV to a partner",
        summary: "Share a worker with a foreign office.",
        keywords: ["workflow", "cv", "share", "partner"],
        access: { paths: ["/admin/employees"] },
        steps: [
          "Employees → PDF button on the worker.",
          "Pick the partner, the colour and Include Passport.",
          "Click Link Partner. The partner can now see the worker.",
          "You can also send them a message in Notifications.",
        ],
        flow: ["Open CV", "Pick partner", "Link Partner", "Send message"],
      },
      {
        id: "wf-close-month",
        title: "Close the books after a check",
        summary: "Check, close and print the report.",
        keywords: ["workflow", "close period", "audit", "report"],
        access: { paths: ["/admin/finances"], roles: [ADMIN] },
        steps: [
          "Finance → check every row.",
          "Periods → View Transactions on the current period.",
          "Click Close Current Period, write a note and confirm.",
          "Open the closed period and click Generate Report.",
        ],
        flow: ["Check", "Close", "Print report"],
      },
      {
        id: "wf-complaint",
        title: "Handle a complaint",
        summary: "From the first call to the end.",
        keywords: ["workflow", "complaint", "follow up"],
        access: { paths: ["/admin/complaints"] },
        steps: [
          "Complaints → Log Complaint. Write what you were told.",
          "Call the partner or employer. Add a Resolution Attempt each time.",
          "Change the status to Investigating.",
          "When solved, write the Complaint Outcome and change the status to Resolved.",
        ],
        flow: ["Add", "Call", "Investigating", "Resolved"],
      },
      {
        id: "wf-partner",
        title: "Partner: check new workers",
        summary: "See new CVs from the agency.",
        keywords: ["workflow", "partner", "cv"],
        access: { roles: [PARTNER] },
        steps: [
          "Read the agency's message in Notifications.",
          "Open Active Employees and find the worker.",
          "Open the CV and click Download CV.",
        ],
        flow: ["Message", "Active Employees", "Download CV"],
      },
    ],
  },

  {
    id: "troubleshooting",
    group: "help",
    title: "Useful Notes & Troubleshooting",
    icon: "bi-life-preserver",
    summary: "Answers to common problems.",
    access: {},
    topics: [
      {
        id: "ts-missing-menu",
        title: "I cannot see a page",
        summary: "Pages depend on your role.",
        keywords: ["missing menu", "permission", "access denied", "cannot see"],
        steps: [
          "Each staff member only sees the pages an admin ticked for them.",
          "Ask an admin to open Users, change your account and tick the page.",
          "Log out and log in again.",
        ],
      },
      {
        id: "ts-view-only",
        title: "“View only — created by another admin”",
        summary: "Why you cannot change some items.",
        keywords: ["view only", "another admin", "cannot edit", "ownership"],
        access: { roles: [ADMIN] },
        steps: [
          "Each admin can only change or delete what they made.",
          "Ask the admin who made it to change it.",
        ],
      },
      {
        id: "ts-logged-out",
        title: "I was logged out",
        summary: "This happens after some time.",
        keywords: ["logged out", "session expired", "login again"],
        steps: [
          "For safety, the system logs you out after some time.",
          "Log in again. Save your work often so you do not lose it.",
        ],
      },
      {
        id: "ts-upload",
        title: "My file does not upload",
        summary: "Check the file type and size.",
        keywords: ["upload", "file too large", "image", "pdf", "size"],
        steps: [
          "Photos: JPG, PNG or WEBP, smaller than 5 MB.",
          "Papers: pictures, PDF or Word.",
          "Check your internet and try again.",
        ],
      },
      {
        id: "ts-unpaid-invoice",
        title: "“already has an unpaid invoice”",
        summary: "One open invoice per worker.",
        keywords: ["unpaid invoice", "invoice conflict", "cannot add employee"],
        access: { paths: ["/admin/invoices"] },
        steps: [
          "A worker can go on a new invoice only after the old one is Paid.",
          "Finish or cancel the old invoice, or remove the worker from the new one.",
        ],
      },
      {
        id: "ts-cv-header",
        title: "The CV has no logo at the top",
        summary: "The partner has no CV header picture.",
        keywords: ["cv header", "no header", "partner header"],
        access: { paths: ["/admin/employees"] },
        steps: [
          "Pick a partner first.",
          "If it says the partner has no header, an admin must add one in Users → change the partner.",
        ],
      },
      {
        id: "ts-autofill",
        title: "Autofill does not work",
        summary: "You need the Chrome extension.",
        keywords: ["autofill", "extension", "chrome"],
        access: { paths: ["/admin/autofill"] },
        steps: [
          "Use Google Chrome on a computer.",
          "Check that the agency Autofill extension is installed and on.",
          "Pick the workers again in Employees.",
        ],
      },
      {
        id: "ts-reply-email",
        title: "Reply by email does nothing",
        summary: "No mail program is set up on this computer.",
        keywords: ["reply", "email", "mail app", "nothing happens", "mailto", "gmail", "outlook"],
        access: { paths: ["/admin/messages"] },
        steps: [
          "Default mail app needs a mail program (like Outlook or Mail) set up on the computer.",
          "Click Reply by email again and pick Gmail or Outlook on the web instead.",
          "Or click Copy email address and paste it into the mail you use.",
        ],
      },
      {
        id: "ts-print",
        title: "Printing tips",
        summary: "Get clean printed pages.",
        keywords: ["print", "pdf", "margins", "background"],
        steps: [
          "In the print window pick Save as PDF to keep a copy.",
          "Turn on Background graphics so colours and stamps print.",
          "Use A4 paper.",
        ],
      },
    ],
  },
];

export default MANUAL_MODULES;
